import "./globals.css";
import { Inter } from "next/font/google";
import { CounterProvider } from "@/app/context/CounterProvider";

const intr = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Create Next App",
    template: `%s | Next App`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={intr.className}>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  );
}
